name       : pandoc-citeproc
version    : 0.14.3.1
release    : 2
source     :
    - http://hackage.haskell.org/package/pandoc-citeproc-0.14.3.1/pandoc-citeproc-0.14.3.1.tar.gz : 42c0b2c8365441bf884daa6202e6ed01b42181cf255406c88b3b31cd27cb467a
license    : BSD-3-Clause
component  : office
summary    : The pandoc-citeproc library exports functions for using the citeproc system with pandoc.
description: |
    The pandoc-citeproc library exports functions for using the citeproc system with pandoc.
builddeps  :
    - ghc-devel
    - haskell-aeson-pretty
    - haskell-cabal-install
    - haskell-file-embed
    - haskell-hs-bibutils
    - haskell-rfc5051
    - haskell-setenv
    - haskell-split
    - haskell-text-icu
    - haskell-xml-conduit
    - pandoc-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
