name       : pandoc-citeproc
version    : 0.11.1.1
release    : 1
source     :
    - https://hackage.haskell.org/package/pandoc-citeproc-0.11.1.1/pandoc-citeproc-0.11.1.1.tar.gz : 9263721ae0017a48f884366eca37955d6983e7cf8571fafbccb49f28ab12e300
license    : BSD-3-Clause
component  : office
summary    : The pandoc-citeproc library exports functions for using the citeproc system with pandoc.
description: |
    The pandoc-citeproc library exports functions for using the citeproc system with pandoc.
builddeps  :
    - ghc-devel
    - haskell-aeson-pretty
    - haskell-cabal-install
    - haskell-file-embed
    - haskell-hs-bibutils
    - haskell-rfc5051
    - haskell-setenv
    - haskell-split
    - haskell-text-icu
    - haskell-xml-conduit
    - pandoc-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register    