name       : pandoc-citeproc
version    : 0.16.2
release    : 3
source     :
    - https://hackage.haskell.org/package/pandoc-citeproc-0.16.2/pandoc-citeproc-0.16.2.tar.gz : 5b6725b003474f19fd7de65f3371a015a7b210b42543fe952f2bc4c7d509b596
license    : BSD-3-Clause
component  : office
summary    : The pandoc-citeproc library exports functions for using the citeproc system with pandoc.
description: |
    The pandoc-citeproc library exports functions for using the citeproc system with pandoc.
builddeps  :
    - haskell-cabal-install
    - haskell-file-embed-devel
    - haskell-hs-bibutils-devel
    - haskell-network-devel
    - haskell-rfc5051-devel
    - haskell-setenv-devel
    - haskell-text-icu-devel
    - haskell-xml-conduit-devel
    - haskell-yaml-devel
    - pandoc-devel
rundeps    :
    - devel :
        - haskell-file-embed-devel
        - haskell-hs-bibutils-devel
        - haskell-network-devel
        - haskell-rfc5051-devel
        - haskell-setenv-devel
        - haskell-text-icu-devel
        - haskell-xml-conduit-devel
        - haskell-yaml-devel
        - pandoc-devel
networking : yes
setup      : |
    sed -i "s|< 1.5|< 1.6|g" pandoc-citeproc.cabal # aeson
    sed -i "s|< 3.1|< 3.2|g" pandoc-citeproc.cabal # network
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
